= C, C++, D Bare Metal Toolchain Builder
Christoph Engelbert <https://github.com/noctarius[@noctarius2k]>
// Settings:
:compat-mode!:
:idseparator: -
// Aliases:
:project-name: dlang-arm-bare-metal README
:project-handle: dlang-arm-bare-metal-readme
:toc:

This toolchain builder script will automatically download, configure, build and install a full bare metal toolchain for C, C++ and D
(at the moment only Cortex-A8 but it is just not yet configurable). This toolchain consists of the typical tools like GCC, AS, LD and
other GNU tools. In addition it will generate GDB, GDC and QEMU for the ARM target platform.

== Usage

The toolchain builder can be downloaded and executed in a single line of code, however it is recommended to create a subdirectory first.
To sucessfully build the toolchain some operating systems might have additional tools or libraries to be installed. Please see the
section about your operating system first.

```
# Create a new directory and switch to it
mkdir toolchain && cd toolchain

# Download and execute the toolchain builder
bash <(curl -s https://raw.githubusercontent.com/noctarius/dlang-arm-bare-metal/master/toolchain-build.sh)
```

While building (due to downloads, extraction and building) the builder might take up up to 5GB diskspace. Please make sure the necessary
amount of free diskspace is available, otherwise the build will fail.

== What Is In The Toolchain?

The toolchain consists of the GNU toolchain, the GCC compiler, GDC as the D compiler, newlib as the common stdlib implementation, GDB and QEMU compiled for ARM emulation.

== Supported OS

At the moment Ubuntu and OS X is supported but more operating systems are going to be supported in the near future.

  * Linux
  ** Ubunutu 15.10 [tested]
  * OS X
  ** 10.11 [tested]

== Ubuntu Builds

Building on Ubuntu requires some tools and libraries to be installed, the follwing apt-get call will install those. Install those first:

```
apt-get install binutils gcc g++ make autoconf texinfo zlib1g-dev python \
  pkg-config libglib2.0-dev libtool shtool autogen
```

== OS X Builds

Building on OS X obviously requires XCode to be installed. Please use the App Store to install XCode before you try to execute the 
toolchain builder.

The XCode link:https://itunes.apple.com/de/app/xcode/id497799835[App Store Link]

== What Is Missing?

At the moment there is not yet a D library. I'm looking forward to integrate a minimalistic D lib to have most common language features supported, however this is not an easy task and I probably will reuse an existing implementation as a base.

Also additional supported / tested operating systems are missing. Writing bash scripts for multiple OS' is not an easy task since provided tools often behave slightly different or have different syntax. The script however is prepared to recognize the most common Linux or BSD distributions and any kind of help is very appreciated :)
